name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip source code
        run: zip -r -x .git source.zip . -x ".git/*"

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Build for Firefox
        run: bun run buildAllFirefox && zip -r firefox.zip ./extension/build

      - name: Release on AMO
        uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: gimloader@thelazysquid.github.io
          xpi-path: firefox.zip
          source-file-path: source.zip
          approval-notes: |
            To build from source:
            1. Install bun from bun.com
            2. bun i --frozen-lockfile
            3. bun run buildAllFirefox
            The extension will be output in ./extension/build
          jwt-issuer: ${{ secrets.AMO_JWT_ISSUER }}
          jwt-secret: ${{ secrets.AMO_JWT_SECRET }}

      - name: Build for Chrome
        run: bun run buildAllChrome && zip -r chrome.zip ./extension/build

      - name: Release on Chrome Webstore
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: chrome.zip
          extension-id: ngbhofnofkggjbpkpnogcdfdgjkpmgka
          client-id: ${{ secrets.CRX_CLIENT_ID }}
          client-secret: ${{ secrets.CRX_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CRX_REFRESH_TOKEN }}